"""
Generate MedTrace_FL_Colab.ipynb
Clones github.com/vivek797029/MEDTRACE and runs the real production pipeline.
"""
import json

cells = []

def md(*lines):
    cells.append({"cell_type": "markdown", "metadata": {}, "source": list(lines)})

def code(*lines):
    cells.append({
        "cell_type": "code", "metadata": {},
        "execution_count": None, "outputs": [],
        "source": list(lines),
    })


# ── Cell 1: Title ─────────────────────────────────────────────────────────────
md(
    "# 🏥 MedTrace FL — Full Production Training\n",
    "\n",
    "Runs the **exact codebase** built over multiple sessions:\n",
    "- Federated Averaging (FedAvg) with TinyLlama 1.1B + LoRA\n",
    "- Adaptive per-client Differential Privacy (novel research contribution)\n",
    "- Streaming aggregation, HospitalRegistry, per-client failure isolation\n",
    "- Full evaluation system, experiment tracking, comparison plots\n",
    "- Auto-resume on Colab disconnect via Google Drive checkpoints\n",
    "\n",
    "---\n",
    "## ⚡ GPU Unit Budget (65 units)\n",
    "| GPU | Units/hr | Full 20 rounds | Verdict |\n",
    "|-----|----------|---------------|---------|\n",
    "| T4  | ~1.8     | ~10–13 units  | ✅ Best value |\n",
    "| L4  | ~2.8     | ~7–10 units   | ✅ Faster |\n",
    "| A100 | ~9.6    | ~18–22 units  | ⚠️ Pricey |\n",
    "\n",
    "**Recommended: T4 GPU** — Runtime → Change runtime type → T4 GPU\n",
    "\n",
    "## 🔄 Auto-Resume\n",
    "Every round is checkpointed to Google Drive. If Colab disconnects, just **Run All** again.\n",
)

# ── Cell 2: GPU check + Drive mount ──────────────────────────────────────────
code(
    "# ── Step 1: Check GPU + Mount Google Drive ───────────────────────────────\n",
    "import torch, os\n",
    "\n",
    "print('=' * 60)\n",
    "if torch.cuda.is_available():\n",
    "    name = torch.cuda.get_device_name(0)\n",
    "    mem  = torch.cuda.get_device_properties(0).total_memory / 1e9\n",
    "    print(f'✅  GPU : {name}')\n",
    "    print(f'    VRAM: {mem:.1f} GB')\n",
    "else:\n",
    "    print('❌  No GPU detected!')\n",
    "    print('   Runtime → Change runtime type → T4 GPU, then Re-run All')\n",
    "    raise SystemExit('Enable GPU first.')\n",
    "\n",
    "from google.colab import drive\n",
    "if not os.path.exists('/content/drive/MyDrive'):\n",
    "    drive.mount('/content/drive')\n",
    "print('✅  Drive mounted')\n",
    "print('=' * 60)\n",
)

# ── Cell 3: Clone repo + install deps ────────────────────────────────────────
code(
    "# ── Step 2: Clone MedTrace repo + install dependencies ───────────────────\n",
    "import subprocess, sys\n",
    "\n",
    "REPO_URL = 'https://github.com/vivek797029/MEDTRACE.git'\n",
    "REPO_DIR = '/content/MEDTRACE'\n",
    "\n",
    "if os.path.exists(REPO_DIR):\n",
    "    print('Repo already cloned — pulling latest changes...')\n",
    "    subprocess.run(['git', '-C', REPO_DIR, 'pull'], check=True)\n",
    "else:\n",
    "    print(f'Cloning {REPO_URL} ...')\n",
    "    subprocess.run(['git', 'clone', REPO_URL, REPO_DIR], check=True)\n",
    "\n",
    "print('Installing dependencies...')\n",
    "subprocess.run([\n",
    "    sys.executable, '-m', 'pip', 'install', '-q',\n",
    "    'transformers>=4.38', 'datasets', 'peft>=0.9',\n",
    "    'accelerate', 'bitsandbytes', 'matplotlib', 'numpy',\n",
    "], check=True)\n",
    "\n",
    "# Add src/ to Python path so all project modules are importable\n",
    "SRC = os.path.join(REPO_DIR, 'src')\n",
    "if SRC not in sys.path:\n",
    "    sys.path.insert(0, SRC)\n",
    "\n",
    "print('\\n✅  Repo ready. Files in src/:')\n",
    "for f in sorted(os.listdir(SRC)):\n",
    "    if f.endswith('.py'):\n",
    "        print(f'   {f}')\n",
)

# ── Cell 4: Configuration ─────────────────────────────────────────────────────
code(
    "# ── Step 3: Configure the experiment ─────────────────────────────────────\n",
    "# All settings live here. Edit and re-run this cell to change config.\n",
    "\n",
    "from fl_config import (\n",
    "    FLConfig, DPConfig, AdaptiveDPConfig, LoRAConfig,\n",
    "    TrainingConfig, EvalConfig, TrackerConfig, HospitalRegistry,\n",
    ")\n",
    "\n",
    "# ── How many hospitals? ───────────────────────────────────────────────────\n",
    "NUM_HOSPITALS = 3          # 3–10 supported; more = longer per round\n",
    "\n",
    "# ── Federated Learning ───────────────────────────────────────────────────\n",
    "FL_ROUNDS    = 20          # Full run. Use 2 to smoke-test first.\n",
    "LOCAL_EPOCHS = 1\n",
    "\n",
    "# ── Differential Privacy ─────────────────────────────────────────────────\n",
    "DP_ON        = True\n",
    "DP_EPSILON   = 8.0         # Lower = more private, more noise\n",
    "DP_DELTA     = 1e-5\n",
    "\n",
    "# ── Adaptive DP (novel contribution) ─────────────────────────────────────\n",
    "ADAPTIVE_ON  = True        # Per-client ε based on loss + gradient sensitivity\n",
    "\n",
    "# ── Google Drive paths ───────────────────────────────────────────────────\n",
    "DRIVE_ROOT   = '/content/drive/MyDrive/MedTrace'\n",
    "CKPT_DIR     = f'{DRIVE_ROOT}/checkpoints'\n",
    "OUTPUT_DIR   = f'{DRIVE_ROOT}/outputs'\n",
    "\n",
    "os.makedirs(CKPT_DIR,   exist_ok=True)\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "\n",
    "# ── Build FLConfig using the real production dataclasses ─────────────────\n",
    "cfg = FLConfig(\n",
    "    base_model   = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0',\n",
    "    fl_rounds    = FL_ROUNDS,\n",
    "    local_epochs = LOCAL_EPOCHS,\n",
    "    hospitals    = HospitalRegistry.build(NUM_HOSPITALS),\n",
    "    lora         = LoRAConfig(r=8, alpha=16, dropout=0.05),\n",
    "    dp           = DPConfig(\n",
    "        enabled      = DP_ON,\n",
    "        epsilon      = DP_EPSILON,\n",
    "        delta        = DP_DELTA,\n",
    "        max_grad_norm= 1.0,\n",
    "    ),\n",
    "    adaptive_dp  = AdaptiveDPConfig(\n",
    "        enabled              = ADAPTIVE_ON,\n",
    "        ema_alpha            = 0.1,\n",
    "        min_epsilon_fraction = 0.1,\n",
    "    ),\n",
    "    training     = TrainingConfig(\n",
    "        batch_size                  = 4,\n",
    "        gradient_accumulation_steps = 4,\n",
    "        learning_rate               = 2e-4,\n",
    "        max_length                  = 512,\n",
    "    ),\n",
    "    eval         = EvalConfig(\n",
    "        enabled              = True,\n",
    "        eval_every_n_rounds  = 5,\n",
    "        num_eval_samples     = 200,\n",
    "    ),\n",
    "    tracker      = TrackerConfig(backend='none'),  # change to 'wandb' or 'mlflow' if you want\n",
    "    output_dir   = OUTPUT_DIR,\n",
    ")\n",
    "\n",
    "import math\n",
    "print('Configuration')\n",
    "print(f'  Hospitals  : {cfg.num_hospitals} ({list(cfg.hospitals.keys())})')\n",
    "print(f'  Rounds     : {cfg.fl_rounds}')\n",
    "print(f'  Base model : {cfg.base_model}')\n",
    "print(f'  LoRA       : r={cfg.lora.r} alpha={cfg.lora.alpha}')\n",
    "print(f'  DP         : {\"ON\" if cfg.dp.enabled else \"OFF\"}',\n",
    "      f'ε={cfg.dp.epsilon} δ={cfg.dp.delta} σ={cfg.dp.sigma:.4f}' if cfg.dp.enabled else '')\n",
    "print(f'  Adaptive DP: {\"ON\" if cfg.adaptive_dp.enabled else \"OFF\"}')\n",
    "print(f'  Batch      : {cfg.training.batch_size} × {cfg.training.gradient_accumulation_steps} = '\n",
    "      f'{cfg.training.batch_size * cfg.training.gradient_accumulation_steps} effective')\n",
    "print(f'  Output     : {cfg.output_dir}')\n",
    "print(f'  Checkpoints: {CKPT_DIR}')\n",
)

# ── Cell 5: Run training ──────────────────────────────────────────────────────
code(
    "# ── Step 4: Run the full federated training pipeline ─────────────────────\n",
    "# This calls run_simulation() from the EXACT fl_simulate.py we built.\n",
    "# Auto-resumes from Drive checkpoint if the session was disconnected.\n",
    "\n",
    "from fl_simulate import run_simulation, setup_logging\n",
    "import logging\n",
    "\n",
    "setup_logging(logging.INFO)\n",
    "\n",
    "report = run_simulation(\n",
    "    cfg,\n",
    "    checkpoint_dir = CKPT_DIR,\n",
    ")\n",
    "\n",
    "print('\\n' + '=' * 60)\n",
    "print('TRAINING COMPLETE')\n",
    "print(f'  Total time : {report[\"total_training_time\"] / 60:.1f} min')\n",
    "print(f'  Rounds done: {len(report[\"round_metrics\"])}')\n",
    "if report[\"round_metrics\"]:\n",
    "    last = report[\"round_metrics\"][-1]\n",
    "    print(f'  Final loss : {last[\"avg_loss\"]:.4f}')\n",
    "    print(f'  Divergence : {last[\"weight_divergence\"]:.6f}')\n",
    "if \"adaptive_dp_summary\" in report:\n",
    "    print('\\nAdaptive DP budget per hospital:')\n",
    "    for hid, s in report[\"adaptive_dp_summary\"][\"per_client\"].items():\n",
    "        print(f'  {hid}: spent={s[\"budget_spent\"]:.3f} / {cfg.dp.epsilon}')\n",
    "print('=' * 60)\n",
)

# ── Cell 6: Plots ─────────────────────────────────────────────────────────────
code(
    "# ── Step 5: Generate training plots ──────────────────────────────────────\n",
    "# Uses the real ResultsPlotter + EvalAccumulator from our codebase.\n",
    "\n",
    "import matplotlib\n",
    "matplotlib.use('Agg')\n",
    "import matplotlib.pyplot as plt\n",
    "from fl_evaluator import EvalAccumulator, EvalResult\n",
    "from fl_plots import ResultsPlotter\n",
    "\n",
    "# Build accumulator from the training report\n",
    "acc = EvalAccumulator()\n",
    "acc.set_metadata(fl_rounds=cfg.fl_rounds, num_hospitals=cfg.num_hospitals,\n",
    "                 dp_epsilon=cfg.dp.epsilon, adaptive_dp=cfg.adaptive_dp.enabled)\n",
    "\n",
    "for rm in report['round_metrics']:\n",
    "    rn = rm['round']\n",
    "    acc.add_eval_result(EvalResult(\n",
    "        run_label            = 'MedTrace FL',\n",
    "        round_num            = rn,\n",
    "        accuracy             = 0.0,   # filled by run_eval.py; 0 here (training-only)\n",
    "        loss                 = rm['avg_loss'],\n",
    "        perplexity           = 0.0,\n",
    "        num_eval_samples     = rm['total_samples'],\n",
    "        elapsed_seconds      = rm['aggregation_time'],\n",
    "        privacy_budget_spent = 0.0,\n",
    "    ))\n",
    "    for hid, m in rm.get('hospital_metrics', {}).items():\n",
    "        acc.add_client_metrics(hid, m)\n",
    "\n",
    "plot_dir = os.path.join(OUTPUT_DIR, 'plots')\n",
    "os.makedirs(plot_dir, exist_ok=True)\n",
    "plotter  = ResultsPlotter(output_dir=plot_dir, fmt='png', dpi=120)\n",
    "paths    = plotter.save_all(acc)\n",
    "\n",
    "# Show inline\n",
    "for path in paths:\n",
    "    print(f'Plot: {path}')\n",
    "    img = plt.imread(path)\n",
    "    fig, ax = plt.subplots(figsize=(12, 5))\n",
    "    ax.imshow(img); ax.axis('off')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "# Also save the JSON results\n",
    "results_json = os.path.join(OUTPUT_DIR, 'results.json')\n",
    "acc.save_json(results_json)\n",
    "print(f'Results saved: {results_json}')\n",
)

# ── Cell 7: Evaluate ──────────────────────────────────────────────────────────
code(
    "# ── Step 6: Evaluate the trained model ───────────────────────────────────\n",
    "# Runs inference on sample clinical questions.\n",
    "\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
    "from peft import PeftModel\n",
    "\n",
    "MODEL_SAVE_DIR = os.path.join(cfg.global_model_dir,\n",
    "                              f'round_{cfg.fl_rounds - 1}')\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "\n",
    "print(f'Loading model from {MODEL_SAVE_DIR} ...')\n",
    "tokenizer = AutoTokenizer.from_pretrained(MODEL_SAVE_DIR)\n",
    "base      = AutoModelForCausalLM.from_pretrained(\n",
    "    cfg.base_model, torch_dtype=torch.float32)\n",
    "model     = PeftModel.from_pretrained(base, MODEL_SAVE_DIR)\n",
    "model.to(device).eval()\n",
    "print('Model ready.\\n')\n",
    "\n",
    "EVAL_QS = [\n",
    "    ('Cardiology',\n",
    "     'A 62-year-old man with hypertension presents with crushing substernal chest pain '\n",
    "     'radiating to the left arm for 45 minutes, diaphoresis, and nausea. '\n",
    "     'ECG shows ST elevation in leads II, III, aVF. What is the immediate management?'),\n",
    "    ('Neurology',\n",
    "     'A 55-year-old woman has sudden onset left-sided weakness, facial droop, and slurred '\n",
    "     'speech 2 hours ago. CT head: no hemorrhage. Blood glucose: 110 mg/dL. Next step?'),\n",
    "    ('Infectious Disease',\n",
    "     'A returned traveller from sub-Saharan Africa has cyclic fever, rigors, headache, '\n",
    "     'splenomegaly for 5 days. Blood smear: ring-form trophozoites. Treatment?'),\n",
    "]\n",
    "\n",
    "for specialty, question in EVAL_QS:\n",
    "    prompt = (f'<|system|>\\n{cfg.system_msg}</s>\\n'\n",
    "              f'<|user|>\\n{question}</s>\\n<|assistant|>\\n')\n",
    "    inputs = tokenizer(prompt, return_tensors='pt').to(device)\n",
    "    with torch.no_grad():\n",
    "        out = model.generate(\n",
    "            **inputs, max_new_tokens=400, temperature=0.7,\n",
    "            do_sample=True, pad_token_id=tokenizer.eos_token_id,\n",
    "            repetition_penalty=1.1,\n",
    "        )\n",
    "    response = tokenizer.decode(\n",
    "        out[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
    "    print(f'[{specialty}]')\n",
    "    print(f'Q: {question[:100]}...')\n",
    "    print(f'A: {response[:600]}')\n",
    "    print('─' * 70 + '\\n')\n",
    "\n",
    "del model, base\n",
    "if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
)

# ── Cell 8: Interactive chat ──────────────────────────────────────────────────
code(
    "# ── Step 7: Interactive chat with the federated model ────────────────────\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
    "from peft import PeftModel\n",
    "\n",
    "MODEL_SAVE_DIR = os.path.join(cfg.global_model_dir,\n",
    "                              f'round_{cfg.fl_rounds - 1}')\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "\n",
    "base  = AutoModelForCausalLM.from_pretrained(cfg.base_model, torch_dtype=torch.float32)\n",
    "model = PeftModel.from_pretrained(base, MODEL_SAVE_DIR)\n",
    "model.to(device).eval()\n",
    "print('Ready. Type your clinical question. Type quit to exit.\\n')\n",
    "\n",
    "while True:\n",
    "    q = input('Your question: ').strip()\n",
    "    if q.lower() in ('quit', 'exit', 'q', ''): break\n",
    "    prompt = f'<|system|>\\n{cfg.system_msg}</s>\\n<|user|>\\n{q}</s>\\n<|assistant|>\\n'\n",
    "    inputs = tokenizer(prompt, return_tensors='pt').to(device)\n",
    "    with torch.no_grad():\n",
    "        out = model.generate(\n",
    "            **inputs, max_new_tokens=500, temperature=0.7,\n",
    "            do_sample=True, pad_token_id=tokenizer.eos_token_id,\n",
    "            repetition_penalty=1.1,\n",
    "        )\n",
    "    ans = tokenizer.decode(out[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
    "    print(f'\\n{\"═\"*65}\\n{ans}\\n{\"═\"*65}\\n')\n",
)

# ── Build notebook ────────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4, "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4", "toc_visible": True},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU",
    },
    "cells": cells,
}

out = "/sessions/magical-serene-newton/mnt/Downloads/medtrace/MedTrace_FL_Colab.ipynb"
with open(out, "w") as f:
    json.dump(notebook, f, indent=1)
print(f"Notebook written → {out}")
print(f"Cells: {len(cells)}")
