"""
Generate MedTrace_FL_Colab.ipynb  — production Colab notebook.

Run:
    python3 build_colab_notebook.py
"""
import json, os

cells = []

def md(*lines):
    cells.append({"cell_type": "markdown", "metadata": {}, "source": list(lines)})

def code(*lines):
    cells.append({
        "cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
        "source": list(lines),
    })


# ── Cell 1: Title ────────────────────────────────────────────────────────────
md(
    "# 🏥 MedTrace FL — Privacy-Preserving Federated Medical AI\n",
    "\n",
    "Fine-tunes **TinyLlama 1.1B** across 3 hospital nodes using **Federated Averaging + LoRA + Differential Privacy**.\n",
    "No patient data is ever shared — only noise-protected model weight deltas.\n",
    "\n",
    "---\n",
    "\n",
    "## ⚡ GPU Unit Budget\n",
    "| GPU | Cost/hr | Full 20 rounds | Recommended? |\n",
    "|-----|---------|---------------|--------------|\n",
    "| T4  | ~1.8 units | ~10–13 units | ✅ Best value |\n",
    "| L4  | ~2.8 units | ~7–10 units  | ✅ Faster |\n",
    "| A100 | ~9.6 units | ~18–22 units | ⚠️ Expensive |\n",
    "| V100 | ~3.8 units | ~12–16 units | ✅ Good |\n",
    "\n",
    "**With 65 units: you can comfortably run the full 20-round experiment on any GPU.**\n",
    "\n",
    "## 🔄 Auto-Resume\n",
    "All checkpoints are saved to Google Drive. If the session disconnects, just **Run All** again — training picks up from the last completed round.\n",
    "\n",
    "## 📋 Steps\n",
    "1. **Cell 1** — Install deps + mount Drive + GPU check\n",
    "2. **Cell 2** — Configure experiment (rounds, DP, hospitals)\n",
    "3. **Cell 3** — Run full federated training\n",
    "4. **Cell 4** — Evaluate and plot results\n",
    "5. **Cell 5** — Interactive question-answering\n",
)

# ── Cell 2: Install + setup ──────────────────────────────────────────────────
code(
    "# ── Install dependencies ─────────────────────────────────────────────────\n",
    "import subprocess, sys\n",
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',\n",
    "    'transformers>=4.38', 'datasets', 'peft>=0.9', 'accelerate', 'torch',\n",
    "    'matplotlib', 'numpy'], check=True)\n",
    "\n",
    "import torch, os\n",
    "print('=' * 60)\n",
    "if torch.cuda.is_available():\n",
    "    name = torch.cuda.get_device_name(0)\n",
    "    mem  = torch.cuda.get_device_properties(0).total_memory / 1e9\n",
    "    print(f'✅  GPU: {name}')\n",
    "    print(f'   VRAM: {mem:.1f} GB')\n",
    "else:\n",
    "    print('⚠️  No GPU detected!')\n",
    "    print('   Go to Runtime → Change runtime type → T4 GPU')\n",
    "    raise SystemExit('Please enable GPU before continuing.')\n",
    "\n",
    "from google.colab import drive\n",
    "if not os.path.exists('/content/drive/MyDrive'):\n",
    "    drive.mount('/content/drive')\n",
    "    print('✅  Drive mounted')\n",
    "else:\n",
    "    print('✅  Drive already mounted')\n",
    "print('=' * 60)\n",
)

# ── Cell 3: Configuration ────────────────────────────────────────────────────
code(
    "# ── Experiment Configuration ─────────────────────────────────────────────\n",
    "# Adjust these values to trade off training time vs. model quality.\n",
    "\n",
    "# ── Model ────────────────────────────────────────────────────────────────\n",
    "BASE_MODEL   = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'\n",
    "\n",
    "# ── Federated Learning ───────────────────────────────────────────────────\n",
    "FL_ROUNDS    = 20       # 20 rounds ≈ 10–15 units on T4\n",
    "LOCAL_EPOCHS = 1        # Epochs per hospital per round\n",
    "BATCH_SIZE   = 4        # Reduce to 2 if OOM\n",
    "GRAD_ACCUM   = 4        # Effective batch = BATCH_SIZE × GRAD_ACCUM = 16\n",
    "MAX_LENGTH   = 512      # Token sequence length\n",
    "LR           = 2e-4\n",
    "\n",
    "# ── LoRA ─────────────────────────────────────────────────────────────────\n",
    "LORA_R       = 8\n",
    "LORA_ALPHA   = 16\n",
    "LORA_TARGETS = ['q_proj', 'v_proj']\n",
    "\n",
    "# ── Differential Privacy (Gaussian mechanism) ────────────────────────────\n",
    "DP_ENABLED       = True\n",
    "DP_EPSILON       = 8.0   # (ε, δ)-DP guarantee; lower = more private, more noise\n",
    "DP_DELTA         = 1e-5\n",
    "DP_MAX_GRAD_NORM = 1.0   # Clipping threshold C\n",
    "\n",
    "# ── Adaptive DP ──────────────────────────────────────────────────────────\n",
    "ADAPTIVE_DP      = True  # Per-client ε allocation based on loss & sensitivity\n",
    "ADAPTIVE_EMA     = 0.1   # EMA smoothing for gradient sensitivity\n",
    "ADAPTIVE_FLOOR   = 0.1   # Min fraction of base ε (prevents starvation)\n",
    "\n",
    "# ── Hospital registry ────────────────────────────────────────────────────\n",
    "HOSPITALS = {\n",
    "    'hospital_A': {\n",
    "        'name': 'Metro General (Cardiology)',\n",
    "        'location': 'New York, USA',\n",
    "        'keywords': ['heart', 'cardiac', 'coronary', 'chest pain', 'myocardial',\n",
    "                     'arrhythmia', 'angina', 'aortic', 'palpitation'],\n",
    "        'num_samples': 1500,\n",
    "        'specialty_ratio': 0.6,\n",
    "    },\n",
    "    'hospital_B': {\n",
    "        'name': 'Royal London (Neurology)',\n",
    "        'location': 'London, UK',\n",
    "        'keywords': ['brain', 'neuro', 'seizure', 'headache', 'stroke',\n",
    "                     'cognitive', 'dementia', 'nerve', 'paralysis'],\n",
    "        'num_samples': 1200,\n",
    "        'specialty_ratio': 0.6,\n",
    "    },\n",
    "    'hospital_C': {\n",
    "        'name': 'AIIMS Delhi (Infectious Disease)',\n",
    "        'location': 'New Delhi, India',\n",
    "        'keywords': ['infection', 'fever', 'bacteria', 'virus', 'antibiotic',\n",
    "                     'sepsis', 'tuberculosis', 'malaria', 'typhoid'],\n",
    "        'num_samples': 1300,\n",
    "        'specialty_ratio': 0.65,\n",
    "    },\n",
    "}\n",
    "\n",
    "# ── Paths ────────────────────────────────────────────────────────────────\n",
    "DRIVE_ROOT   = '/content/drive/MyDrive/MedTrace'\n",
    "CKPT_DIR     = f'{DRIVE_ROOT}/checkpoints'\n",
    "MODEL_DIR    = f'{DRIVE_ROOT}/federated-model'\n",
    "RESULTS_DIR  = f'{DRIVE_ROOT}/results'\n",
    "SYSTEM_MSG   = ('You are MedTrace, a federated clinical reasoning system. '\n",
    "                'Provide step-by-step, evidence-based diagnostic reasoning.')\n",
    "\n",
    "for d in [CKPT_DIR, MODEL_DIR, RESULTS_DIR]:\n",
    "    os.makedirs(d, exist_ok=True)\n",
    "\n",
    "import math\n",
    "DP_SIGMA = DP_MAX_GRAD_NORM * math.sqrt(2 * math.log(1.25 / DP_DELTA)) / DP_EPSILON\n",
    "print('Configuration summary')\n",
    "print(f'  Rounds: {FL_ROUNDS} | Hospitals: {len(HOSPITALS)} | Local epochs: {LOCAL_EPOCHS}')\n",
    "print(f'  LoRA r={LORA_R}, alpha={LORA_ALPHA} | Batch={BATCH_SIZE}×{GRAD_ACCUM}')\n",
    "if DP_ENABLED:\n",
    "    print(f'  DP: ε={DP_EPSILON}, δ={DP_DELTA}, σ={DP_SIGMA:.4f}, C={DP_MAX_GRAD_NORM}')\n",
    "    print(f'  Adaptive DP: {ADAPTIVE_DP} | EMA α={ADAPTIVE_EMA} | floor={ADAPTIVE_FLOOR}')\n",
    "    per_round_eps = DP_EPSILON / math.sqrt(FL_ROUNDS)\n",
    "    print(f'  Per-round ε: {per_round_eps:.4f} (advanced composition)')\n",
    "else:\n",
    "    print('  DP: disabled (no-privacy baseline)')\n",
    "print(f'  Drive checkpoints: {CKPT_DIR}')\n",
)

# ── Cell 4: Core Classes ─────────────────────────────────────────────────────
code(
    "# ── Core Classes: Hospital Client + Adaptive DP + Federated Server ───────\n",
    "import copy, re, time, json\n",
    "import numpy as np\n",
    "from collections import OrderedDict\n",
    "from datasets import load_dataset\n",
    "from transformers import (\n",
    "    AutoTokenizer, AutoModelForCausalLM,\n",
    "    TrainingArguments, Trainer, DataCollatorForLanguageModeling,\n",
    ")\n",
    "from peft import LoraConfig, get_peft_model, PeftModel\n",
    "\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "\n",
    "\n",
    "# ── Adaptive DP State ──────────────────────────────────────────────────────\n",
    "class ClientDPState:\n",
    "    def __init__(self, hospital_id, init_sensitivity=1.0):\n",
    "        self.hospital_id    = hospital_id\n",
    "        self.sensitivity_ema = init_sensitivity\n",
    "        self.budget_spent   = 0.0\n",
    "        self.latest_loss    = float('inf')\n",
    "        self.round_epsilons = []\n",
    "\n",
    "    def record_loss(self, loss):   self.latest_loss = float(loss)\n",
    "    def update_sensitivity(self, norm, alpha):\n",
    "        self.sensitivity_ema = alpha * norm + (1.0 - alpha) * self.sensitivity_ema\n",
    "\n",
    "\n",
    "class AdaptiveDPMechanism:\n",
    "    \"\"\"\n",
    "    Per-client noise calibration.\n",
    "    Converged hospitals (low loss) get more ε → less noise → cleaner updates.\n",
    "    \"\"\"\n",
    "    def __init__(self, hospital_ids, global_eps, delta, fl_rounds,\n",
    "                 init_sensitivity=1.0, ema_alpha=0.1, min_frac=0.1):\n",
    "        self.global_epsilon = global_eps\n",
    "        self.delta      = delta\n",
    "        self.fl_rounds  = fl_rounds\n",
    "        self.ema_alpha  = ema_alpha\n",
    "        self.min_frac   = min_frac\n",
    "        self.states = {hid: ClientDPState(hid, init_sensitivity) for hid in hospital_ids}\n",
    "        print(f'Adaptive DP: ε={global_eps} δ={delta} α={ema_alpha} floor={min_frac}')\n",
    "\n",
    "    def compute_allocation(self, round_num):\n",
    "        base_eps = self.global_epsilon / math.sqrt(self.fl_rounds)\n",
    "        losses = {hid: s.latest_loss for hid, s in self.states.items()}\n",
    "        # Softmax over inverse loss (low loss → high weight → more ε)\n",
    "        inv = {hid: (1.0 / l if l > 0 and l != float('inf') else 1.0)\n",
    "               for hid, l in losses.items()}\n",
    "        total_inv = sum(inv.values())\n",
    "        weights   = {hid: v / total_inv for hid, v in inv.items()}\n",
    "        n = len(self.states)\n",
    "        alloc = {}\n",
    "        for hid, w in weights.items():\n",
    "            s = self.states[hid]\n",
    "            eps = max(base_eps * n * w, base_eps * self.min_frac)\n",
    "            remaining = max(0.0, self.global_epsilon - s.budget_spent)\n",
    "            alloc[hid] = min(eps, remaining)\n",
    "        return alloc\n",
    "\n",
    "    def apply_noise(self, hospital_id, weights, round_num, round_epsilon):\n",
    "        state = self.states[hospital_id]\n",
    "        if round_epsilon <= 0.0:\n",
    "            print(f'  {hospital_id}: budget exhausted, returning unnoised weights')\n",
    "            return weights\n",
    "        clip_norm = state.sensitivity_ema\n",
    "        sigma = clip_norm * math.sqrt(2.0 * math.log(1.25 / self.delta)) / round_epsilon\n",
    "\n",
    "        with torch.no_grad():\n",
    "            flat = torch.cat([p.reshape(-1).float() for p in weights.values()])\n",
    "            actual_norm = torch.norm(flat).item()\n",
    "        state.update_sensitivity(actual_norm, self.ema_alpha)\n",
    "\n",
    "        noisy = OrderedDict()\n",
    "        with torch.no_grad():\n",
    "            for name, param in weights.items():\n",
    "                p = param.float()\n",
    "                norm = torch.norm(p).item()\n",
    "                if norm > clip_norm and norm > 0:\n",
    "                    p = p * (clip_norm / norm)\n",
    "                noisy[name] = p + torch.randn_like(p) * sigma\n",
    "\n",
    "        state.budget_spent += round_epsilon\n",
    "        state.round_epsilons.append(round_epsilon)\n",
    "        print(f'  Adaptive DP | Cᵢ={clip_norm:.3f} σ={sigma:.4f} ε_r={round_epsilon:.4f} '\n",
    "              f'spent={state.budget_spent:.3f}/{self.global_epsilon}')\n",
    "        return noisy\n",
    "\n",
    "    def record_loss(self, hospital_id, loss):\n",
    "        self.states[hospital_id].record_loss(loss)\n",
    "\n",
    "    def summary(self):\n",
    "        return {\n",
    "            hid: {'budget_spent': s.budget_spent, 'sensitivity_ema': s.sensitivity_ema,\n",
    "                  'latest_loss': s.latest_loss, 'rounds': len(s.round_epsilons)}\n",
    "            for hid, s in self.states.items()\n",
    "        }\n",
    "\n",
    "\n",
    "# ── Hospital Client ────────────────────────────────────────────────────────\n",
    "class HospitalClient:\n",
    "    def __init__(self, hospital_id, config):\n",
    "        self.hid          = hospital_id\n",
    "        self.name         = config['name']\n",
    "        self.location     = config['location']\n",
    "        self.keywords     = config['keywords']\n",
    "        self.num_samples  = config['num_samples']\n",
    "        self.spec_ratio   = config['specialty_ratio']\n",
    "        self.local_data   = None\n",
    "        self.budget_spent = 0.0\n",
    "        self.round_losses = []\n",
    "        print(f'  ✓ {self.name} ({self.location})')\n",
    "\n",
    "    def prepare_data(self, full_dataset, round_num):\n",
    "        pattern = re.compile('|'.join(re.escape(k) for k in self.keywords), re.IGNORECASE)\n",
    "        spec_idx, gen_idx = [], []\n",
    "        for i, ex in enumerate(full_dataset):\n",
    "            (spec_idx if pattern.search(ex.get('question', '')) else gen_idx).append(i)\n",
    "\n",
    "        seed = abs(hash(self.hid) + round_num) % (2**32)\n",
    "        rng  = np.random.RandomState(seed)\n",
    "        n = min(self.num_samples, len(full_dataset))\n",
    "        n_spec = min(int(n * self.spec_ratio), len(spec_idx))\n",
    "        n_gen  = n - n_spec\n",
    "\n",
    "        chosen = []\n",
    "        if n_spec > 0 and spec_idx: chosen.extend(rng.choice(spec_idx, n_spec, replace=True))\n",
    "        if n_gen  > 0 and gen_idx:  chosen.extend(rng.choice(gen_idx,  n_gen,  replace=True))\n",
    "        if not chosen: chosen = rng.choice(len(full_dataset), n, replace=True).tolist()\n",
    "        rng.shuffle(chosen)\n",
    "        self.local_data = full_dataset.select(chosen[:n])\n",
    "        print(f'  {self.name}: {len(self.local_data)} samples ({n_spec} specialty, {n_gen} general)')\n",
    "\n",
    "    def _make_lora_config(self):\n",
    "        return LoraConfig(r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=0.05,\n",
    "                          target_modules=LORA_TARGETS, bias='none', task_type='CAUSAL_LM')\n",
    "\n",
    "    def train_local(self, global_weights, tokenizer, round_num,\n",
    "                    base_model=None, adaptive_dp=None, round_epsilon=None):\n",
    "        print(f'\\n  ── {self.name} | Round {round_num+1} ──')\n",
    "        t0 = time.time()\n",
    "\n",
    "        owns_base = base_model is None\n",
    "        if owns_base:\n",
    "            base_model = AutoModelForCausalLM.from_pretrained(\n",
    "                BASE_MODEL, torch_dtype=torch.float32)\n",
    "\n",
    "        base_copy = copy.deepcopy(base_model)\n",
    "        model = get_peft_model(base_copy, self._make_lora_config())\n",
    "        if global_weights is not None:\n",
    "            model.load_state_dict(global_weights, strict=False)\n",
    "        model.to(device).train()\n",
    "\n",
    "        def tokenize_fn(examples):\n",
    "            prompts = [\n",
    "                f'<|system|>\\n{SYSTEM_MSG}</s>\\n<|user|>\\n{q}</s>\\n<|assistant|>\\n'\n",
    "                for q in examples['question']\n",
    "            ]\n",
    "            enc = tokenizer(prompts, truncation=True, max_length=MAX_LENGTH, padding='max_length')\n",
    "            enc['labels'] = enc['input_ids'].copy()\n",
    "            return enc\n",
    "\n",
    "        tok_data = self.local_data.map(tokenize_fn, batched=True,\n",
    "                                       remove_columns=self.local_data.column_names)\n",
    "        tok_data.set_format('torch')\n",
    "\n",
    "        out_dir = f'/content/fl_temp/{self.hid}/round_{round_num}'\n",
    "        os.makedirs(out_dir, exist_ok=True)\n",
    "\n",
    "        args = TrainingArguments(\n",
    "            output_dir=out_dir,\n",
    "            num_train_epochs=LOCAL_EPOCHS,\n",
    "            per_device_train_batch_size=BATCH_SIZE,\n",
    "            gradient_accumulation_steps=GRAD_ACCUM,\n",
    "            learning_rate=LR,\n",
    "            warmup_steps=10,\n",
    "            weight_decay=0.01,\n",
    "            logging_steps=10,\n",
    "            save_strategy='no',\n",
    "            report_to='none',\n",
    "            fp16=torch.cuda.is_available(),\n",
    "            gradient_checkpointing=True,\n",
    "            dataloader_pin_memory=False,\n",
    "        )\n",
    "        trainer = Trainer(\n",
    "            model=model, args=args, train_dataset=tok_data,\n",
    "            data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),\n",
    "        )\n",
    "        trainer.train()\n",
    "        elapsed = time.time() - t0\n",
    "\n",
    "        # Extract LoRA weights\n",
    "        lora_w = OrderedDict(\n",
    "            (name, p.detach().cpu().clone())\n",
    "            for name, p in model.named_parameters() if 'lora_' in name\n",
    "        )\n",
    "\n",
    "        # Apply DP noise\n",
    "        use_adaptive = ADAPTIVE_DP and adaptive_dp is not None and round_epsilon is not None\n",
    "        if use_adaptive:\n",
    "            lora_w = adaptive_dp.apply_noise(self.hid, lora_w, round_num, round_epsilon)\n",
    "            self.budget_spent = adaptive_dp.states[self.hid].budget_spent\n",
    "        elif DP_ENABLED:\n",
    "            with torch.no_grad():\n",
    "                for name in lora_w:\n",
    "                    p = lora_w[name].float()\n",
    "                    norm = torch.norm(p).item()\n",
    "                    if norm > DP_MAX_GRAD_NORM:\n",
    "                        p = p * (DP_MAX_GRAD_NORM / norm)\n",
    "                    lora_w[name] = p + torch.randn_like(p) * DP_SIGMA\n",
    "            per_round_eps = DP_EPSILON / math.sqrt(FL_ROUNDS)\n",
    "            self.budget_spent += per_round_eps\n",
    "            print(f'  Standard DP | σ={DP_SIGMA:.4f} | Budget: {self.budget_spent:.3f}/{DP_EPSILON}')\n",
    "\n",
    "        train_loss = (\n",
    "            trainer.state.log_history[-1].get('train_loss', 0.0)\n",
    "            if trainer.state.log_history else 0.0\n",
    "        )\n",
    "        self.round_losses.append(train_loss)\n",
    "\n",
    "        n_params = sum(p.numel() for p in lora_w.values())\n",
    "        print(f'  Loss={train_loss:.4f} | Time={elapsed:.1f}s | Shared params={n_params:,}')\n",
    "\n",
    "        del model, base_copy, trainer\n",
    "        if owns_base: del base_model\n",
    "        if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
    "\n",
    "        return lora_w, {\n",
    "            'hospital': self.name,\n",
    "            'round': round_num,\n",
    "            'train_loss': train_loss,\n",
    "            'num_samples': len(self.local_data),\n",
    "            'training_time_seconds': round(elapsed, 2),\n",
    "            'lora_params_shared': n_params,\n",
    "            'privacy_budget_spent': self.budget_spent,\n",
    "            'dp_mode': 'adaptive' if use_adaptive else ('standard' if DP_ENABLED else 'none'),\n",
    "        }\n",
    "\n",
    "\n",
    "# ── Federated Server ───────────────────────────────────────────────────────\n",
    "class FederatedServer:\n",
    "    def __init__(self):\n",
    "        self.global_weights = None\n",
    "        self.round_metrics  = []\n",
    "\n",
    "    def _make_lora_config(self):\n",
    "        return LoraConfig(r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=0.05,\n",
    "                          target_modules=LORA_TARGETS, bias='none', task_type='CAUSAL_LM')\n",
    "\n",
    "    def init_global_model(self):\n",
    "        print('Initializing global LoRA model...')\n",
    "        base  = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "        model = get_peft_model(base, self._make_lora_config())\n",
    "        self.global_weights = OrderedDict(\n",
    "            (n, p.detach().cpu().clone())\n",
    "            for n, p in model.named_parameters() if 'lora_' in n\n",
    "        )\n",
    "        n_params = sum(p.numel() for p in self.global_weights.values())\n",
    "        size_kb  = sum(p.element_size() * p.numel() for p in self.global_weights.values()) / 1024\n",
    "        print(f'  LoRA params: {n_params:,} | Size: {size_kb:.1f} KB')\n",
    "        del model, base\n",
    "        if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
    "        return self.global_weights\n",
    "\n",
    "    def aggregate(self, client_updates, round_num):\n",
    "        t0 = time.time()\n",
    "        total_samples = sum(m['num_samples'] for _, m in client_updates.values())\n",
    "        fracs = {hid: m['num_samples'] / total_samples for hid, (_, m) in client_updates.items()}\n",
    "\n",
    "        # Streaming FedAvg — O(2×model_size) memory\n",
    "        aggregated = OrderedDict()\n",
    "        for hid, (weights, metrics) in client_updates.items():\n",
    "            frac = fracs[hid]\n",
    "            for key, param in weights.items():\n",
    "                p = param.float()\n",
    "                aggregated[key] = aggregated.get(key, torch.zeros_like(p)) + frac * p\n",
    "\n",
    "        # Validate\n",
    "        for name, param in aggregated.items():\n",
    "            if torch.isnan(param).any(): raise ValueError(f'NaN in aggregated weight: {name}')\n",
    "            if torch.isinf(param).any(): raise ValueError(f'Inf in aggregated weight: {name}')\n",
    "\n",
    "        self.global_weights = aggregated\n",
    "        elapsed = time.time() - t0\n",
    "\n",
    "        losses      = [m['train_loss'] for _, m in client_updates.values()]\n",
    "        frac_list   = [fracs[hid] for hid in client_updates]\n",
    "        avg_loss    = sum(l * w for l, w in zip(losses, frac_list))\n",
    "\n",
    "        # Weight divergence\n",
    "        divergence = 0.0\n",
    "        count = 0\n",
    "        for hid, (weights, _) in client_updates.items():\n",
    "            for key in aggregated:\n",
    "                if key in weights:\n",
    "                    divergence += torch.norm(weights[key].float() - aggregated[key].float()).item() ** 2\n",
    "                    count += 1\n",
    "        divergence /= max(count, 1)\n",
    "\n",
    "        print(f'  FedAvg | clients={len(client_updates)} | avg_loss={avg_loss:.4f} | '\n",
    "              f'divergence={divergence:.6f} | time={elapsed:.2f}s')\n",
    "        for hid, (_, m) in client_updates.items():\n",
    "            print(f'    {m[\"hospital\"]}: weight={fracs[hid]:.3f} ({m[\"num_samples\"]} samples)')\n",
    "\n",
    "        rm = {'round': round_num, 'avg_loss': avg_loss, 'weight_divergence': divergence,\n",
    "              'total_samples': total_samples, 'num_hospitals': len(client_updates),\n",
    "              'aggregation_time': elapsed,\n",
    "              'hospital_losses': {m['hospital']: m['train_loss']\n",
    "                                  for _, (_, m) in zip(client_updates.keys(), client_updates.items())}}\n",
    "        self.round_metrics.append(rm)\n",
    "        return self.global_weights\n",
    "\n",
    "    def save_model(self, tokenizer, save_dir=None):\n",
    "        d = save_dir or MODEL_DIR\n",
    "        os.makedirs(d, exist_ok=True)\n",
    "        base  = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "        model = get_peft_model(base, self._make_lora_config())\n",
    "        model.load_state_dict(self.global_weights, strict=False)\n",
    "        model.save_pretrained(d)\n",
    "        tokenizer.save_pretrained(d)\n",
    "        del model, base\n",
    "        if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
    "        print(f'  Model saved to: {d}')\n",
    "        return d\n",
    "\n",
    "print('✅  All classes defined')\n",
)

# ── Cell 5: Checkpoint helpers ───────────────────────────────────────────────
code(
    "# ── Checkpoint helpers ────────────────────────────────────────────────────\n",
    "def save_checkpoint(weights, round_num):\n",
    "    path = os.path.join(CKPT_DIR, f'round_{round_num}.pt')\n",
    "    torch.save(weights, path)\n",
    "    with open(os.path.join(CKPT_DIR, 'last_round.txt'), 'w') as f:\n",
    "        f.write(str(round_num))\n",
    "    size_mb = os.path.getsize(path) / (1024 * 1024)\n",
    "    print(f'  ✅ Checkpoint saved: round_{round_num}.pt ({size_mb:.2f} MB)')\n",
    "\n",
    "def load_checkpoint():\n",
    "    marker = os.path.join(CKPT_DIR, 'last_round.txt')\n",
    "    if not os.path.exists(marker):\n",
    "        return None, -1\n",
    "    with open(marker) as f:\n",
    "        last = int(f.read().strip())\n",
    "    path = os.path.join(CKPT_DIR, f'round_{last}.pt')\n",
    "    if not os.path.exists(path):\n",
    "        print(f'  ⚠️  Marker says round {last} but file missing — starting fresh')\n",
    "        return None, -1\n",
    "    weights = torch.load(path, map_location='cpu', weights_only=False)\n",
    "    size_mb = os.path.getsize(path) / (1024 * 1024)\n",
    "    print(f'  ✅ Resumed from round_{last}.pt ({size_mb:.2f} MB)')\n",
    "    return weights, last\n",
    "\n",
    "print('✅  Checkpoint helpers ready')\n",
)

# ── Cell 6: Training loop ────────────────────────────────────────────────────
code(
    "# ── Federated Training Loop ───────────────────────────────────────────────\n",
    "# Run-All safe: resumes from the last Drive checkpoint automatically.\n",
    "\n",
    "print('Loading MedQA USMLE dataset...')\n",
    "dataset   = load_dataset('GBaker/MedQA-USMLE-4-options', split='train')\n",
    "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)\n",
    "if tokenizer.pad_token is None:\n",
    "    tokenizer.pad_token = tokenizer.eos_token\n",
    "print(f'Dataset: {len(dataset):,} examples | Tokenizer: {BASE_MODEL}')\n",
    "\n",
    "print('\\nInitializing hospitals...')\n",
    "hospitals = {hid: HospitalClient(hid, cfg) for hid, cfg in HOSPITALS.items()}\n",
    "\n",
    "server     = FederatedServer()\n",
    "global_w, last_round = load_checkpoint()\n",
    "start_round = last_round + 1\n",
    "\n",
    "if global_w is None:\n",
    "    print('\\nNo checkpoint — starting fresh')\n",
    "    global_w = server.init_global_model()\n",
    "    start_round = 0\n",
    "else:\n",
    "    server.global_weights = global_w\n",
    "    print(f'Resuming from round {start_round + 1}/{FL_ROUNDS}')\n",
    "\n",
    "# Adaptive DP mechanism (per-client ε allocation)\n",
    "adaptive_dp = None\n",
    "if DP_ENABLED and ADAPTIVE_DP:\n",
    "    adaptive_dp = AdaptiveDPMechanism(\n",
    "        hospital_ids=list(hospitals.keys()),\n",
    "        global_eps=DP_EPSILON, delta=DP_DELTA, fl_rounds=FL_ROUNDS,\n",
    "        ema_alpha=ADAPTIVE_EMA, min_frac=ADAPTIVE_FLOOR,\n",
    "    )\n",
    "\n",
    "training_log = []  # per-round summary\n",
    "total_t0     = time.time()\n",
    "\n",
    "for r in range(start_round, FL_ROUNDS):\n",
    "    round_t0 = time.time()\n",
    "    print(f'\\n{\"=\"*65}')\n",
    "    print(f'  ROUND {r+1}/{FL_ROUNDS}')\n",
    "    print(f'{\"=\"*65}')\n",
    "\n",
    "    # Distribute data (non-IID, per-specialty)\n",
    "    for client in hospitals.values():\n",
    "        client.prepare_data(dataset, r)\n",
    "\n",
    "    # Compute per-client ε BEFORE training\n",
    "    round_alloc = {}\n",
    "    if adaptive_dp is not None:\n",
    "        round_alloc = adaptive_dp.compute_allocation(r)\n",
    "        print(f'  Adaptive ε: ' +\n",
    "              ', '.join(f'{hid}={e:.4f}' for hid, e in round_alloc.items()))\n",
    "\n",
    "    # Load shared base model ONCE per round (saves ~30s per round)\n",
    "    print('\\n  Loading shared base model...')\n",
    "    shared_base = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "    shared_base.eval()\n",
    "\n",
    "    # Local training — each hospital trains on its private data\n",
    "    client_updates = {}\n",
    "    failed = []\n",
    "    for hid, client in hospitals.items():\n",
    "        try:\n",
    "            w, m = client.train_local(\n",
    "                global_w, tokenizer, r,\n",
    "                base_model=shared_base,\n",
    "                adaptive_dp=adaptive_dp,\n",
    "                round_epsilon=round_alloc.get(hid),\n",
    "            )\n",
    "            client_updates[hid] = (w, m)\n",
    "        except Exception as exc:\n",
    "            print(f'  ⚠️  {hid} FAILED (skipping): {exc}')\n",
    "            failed.append(hid)\n",
    "\n",
    "    del shared_base\n",
    "    if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
    "\n",
    "    if not client_updates:\n",
    "        print('  ❌ ALL clients failed — skipping round')\n",
    "        continue\n",
    "    if failed:\n",
    "        print(f'  ⚠️  {len(failed)}/{len(hospitals)} clients failed; '\n",
    "              f'aggregating {len(client_updates)} successful clients')\n",
    "\n",
    "    # Record losses for next round's adaptive ε allocation\n",
    "    if adaptive_dp is not None:\n",
    "        for hid, (_, m) in client_updates.items():\n",
    "            adaptive_dp.record_loss(hid, m.get('train_loss', float('inf')))\n",
    "\n",
    "    # Aggregate (streaming FedAvg)\n",
    "    print(f'\\n  Aggregating...')\n",
    "    global_w = server.aggregate(client_updates, r)\n",
    "\n",
    "    # Checkpoint to Drive\n",
    "    save_checkpoint(global_w, r)\n",
    "\n",
    "    round_elapsed = time.time() - round_t0\n",
    "    rounds_done   = r - start_round + 1\n",
    "    avg_t         = (time.time() - total_t0) / rounds_done\n",
    "    eta_min       = (FL_ROUNDS - r - 1) * avg_t / 60\n",
    "\n",
    "    max_budget = max(h.budget_spent for h in hospitals.values())\n",
    "    budget_pct = min(100.0, max_budget / DP_EPSILON * 100) if DP_EPSILON > 0 else 0.0\n",
    "\n",
    "    log_entry = {\n",
    "        'round': r + 1,\n",
    "        'time_seconds': round(round_elapsed, 1),\n",
    "        'avg_loss': server.round_metrics[-1]['avg_loss'],\n",
    "        'weight_divergence': server.round_metrics[-1]['weight_divergence'],\n",
    "        'privacy_budget_pct': round(budget_pct, 2),\n",
    "    }\n",
    "    training_log.append(log_entry)\n",
    "\n",
    "    print(f'\\n  ⏱  Round {r+1} done in {round_elapsed:.0f}s | ETA: {eta_min:.0f} min')\n",
    "    print(f'  📊 avg_loss={log_entry[\"avg_loss\"]:.4f} | '\n",
    "          f'divergence={log_entry[\"weight_divergence\"]:.6f} | '\n",
    "          f'DP budget used: {budget_pct:.1f}%')\n",
    "\n",
    "total_elapsed = time.time() - total_t0\n",
    "print(f'\\n{\"=\"*65}')\n",
    "print(f'  🏁 TRAINING COMPLETE')\n",
    "print(f'  Total time: {total_elapsed/60:.1f} min | Rounds: {FL_ROUNDS - start_round}')\n",
    "print(f'{\"=\"*65}')\n",
    "\n",
    "# Save final model + metadata\n",
    "print('\\nSaving final model to Drive...')\n",
    "server.save_model(tokenizer)\n",
    "\n",
    "report = {\n",
    "    'base_model': BASE_MODEL,\n",
    "    'fl_rounds': FL_ROUNDS,\n",
    "    'hospitals': list(HOSPITALS.keys()),\n",
    "    'dp': {'enabled': DP_ENABLED, 'epsilon': DP_EPSILON, 'delta': DP_DELTA,\n",
    "           'sigma': DP_SIGMA if DP_ENABLED else 0.0, 'adaptive': ADAPTIVE_DP},\n",
    "    'total_training_time_minutes': round(total_elapsed / 60, 2),\n",
    "    'round_log': training_log,\n",
    "    'privacy_budget_summary': adaptive_dp.summary() if adaptive_dp else {},\n",
    "}\n",
    "report_path = os.path.join(RESULTS_DIR, 'training_report.json')\n",
    "with open(report_path, 'w') as f:\n",
    "    json.dump(report, f, indent=2, default=str)\n",
    "print(f'\\nReport saved: {report_path}')\n",
)

# ── Cell 7: Plots ────────────────────────────────────────────────────────────
code(
    "# ── Training Plots ────────────────────────────────────────────────────────\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib\n",
    "matplotlib.rcParams.update({'font.size': 11, 'figure.dpi': 120})\n",
    "\n",
    "if not training_log:\n",
    "    print('No training log — run the training cell first')\n",
    "else:\n",
    "    rounds   = [e['round']             for e in training_log]\n",
    "    losses   = [e['avg_loss']          for e in training_log]\n",
    "    divs     = [e['weight_divergence'] for e in training_log]\n",
    "    budgets  = [e['privacy_budget_pct'] for e in training_log]\n",
    "    times    = [e['time_seconds']      for e in training_log]\n",
    "\n",
    "    fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n",
    "    fig.suptitle('MedTrace FL — Training Summary', fontsize=14, fontweight='bold')\n",
    "\n",
    "    ax = axes[0, 0]\n",
    "    ax.plot(rounds, losses, 'o-', color='#2196F3', linewidth=2, markersize=5)\n",
    "    ax.set_title('Weighted Average Training Loss'); ax.set_xlabel('Round'); ax.set_ylabel('Loss')\n",
    "    ax.grid(True, alpha=0.3); ax.set_xlim(left=1)\n",
    "\n",
    "    ax = axes[0, 1]\n",
    "    ax.plot(rounds, divs, 's-', color='#9C27B0', linewidth=2, markersize=5)\n",
    "    ax.set_title('Weight Divergence (FedAvg Quality)')\n",
    "    ax.set_xlabel('Round'); ax.set_ylabel('Divergence (MSE)')\n",
    "    ax.grid(True, alpha=0.3); ax.set_xlim(left=1)\n",
    "\n",
    "    ax = axes[1, 0]\n",
    "    if DP_ENABLED:\n",
    "        ax.plot(rounds, budgets, '^-', color='#F44336', linewidth=2, markersize=5)\n",
    "        ax.axhline(100, color='red', linestyle='--', linewidth=1, alpha=0.5, label='Budget cap')\n",
    "        ax.set_ylabel('Budget used (%)')\n",
    "    else:\n",
    "        ax.text(0.5, 0.5, 'DP disabled', ha='center', va='center', transform=ax.transAxes)\n",
    "    ax.set_title('Privacy Budget Consumed (ε)'); ax.set_xlabel('Round')\n",
    "    ax.grid(True, alpha=0.3); ax.set_xlim(left=1)\n",
    "\n",
    "    ax = axes[1, 1]\n",
    "    ax.bar(rounds, times, color='#4CAF50', alpha=0.7, width=0.6)\n",
    "    ax.set_title('Time per Round'); ax.set_xlabel('Round'); ax.set_ylabel('Seconds')\n",
    "    ax.grid(True, alpha=0.3, axis='y')\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plot_path = os.path.join(RESULTS_DIR, 'training_summary.png')\n",
    "    plt.savefig(plot_path, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(f'Plot saved: {plot_path}')\n",
    "\n",
    "    # Print summary table\n",
    "    print(f'\\n{\"─\"*50}')\n",
    "    print(f'{\"Round\":>6}  {\"Avg Loss\":>10}  {\"Divergence\":>12}  {\"DP Budget %\":>12}')\n",
    "    print(f'{\"─\"*50}')\n",
    "    for e in training_log:\n",
    "        print(f'{e[\"round\"]:>6}  {e[\"avg_loss\"]:>10.4f}  '\n",
    "              f'{e[\"weight_divergence\"]:>12.6f}  {e[\"privacy_budget_pct\"]:>11.1f}%')\n",
    "    print(f'{\"─\"*50}')\n",
)

# ── Cell 8: Evaluation ───────────────────────────────────────────────────────
code(
    "# ── Evaluate Federated Model ──────────────────────────────────────────────\n",
    "EVAL_QUESTIONS = [\n",
    "    ('Cardiology',\n",
    "     'A 62-year-old man with hypertension and diabetes presents with crushing substernal '\n",
    "     'chest pain radiating to the left arm for 45 minutes, diaphoresis, and nausea. '\n",
    "     'ECG shows ST elevation in leads II, III, aVF. What is the immediate management?'),\n",
    "    ('Neurology',\n",
    "     'A 55-year-old woman presents with sudden onset of left-sided weakness, facial droop, '\n",
    "     'and slurred speech that started 2 hours ago. CT head shows no hemorrhage. '\n",
    "     'Blood glucose is 110 mg/dL. What is the next step?'),\n",
    "    ('Infectious Disease',\n",
    "     'A 30-year-old returned traveller from sub-Saharan Africa presents with cyclic fever, '\n",
    "     'rigors, headache, and splenomegaly for 5 days. Blood smear shows ring-form trophozoites. '\n",
    "     'What is the treatment?'),\n",
    "    ('General',\n",
    "     'A 45-year-old man presents with progressive shortness of breath on exertion, '\n",
    "     'orthopnea, and bilateral pitting oedema. JVP is elevated. What is the diagnosis '\n",
    "     'and initial management?'),\n",
    "]\n",
    "\n",
    "print('Loading federated model for evaluation...')\n",
    "base  = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "model = PeftModel.from_pretrained(base, MODEL_DIR)\n",
    "model.to(device).eval()\n",
    "print(f'Model loaded from: {MODEL_DIR}\\n')\n",
    "\n",
    "eval_results = []\n",
    "for specialty, question in EVAL_QUESTIONS:\n",
    "    prompt = f'<|system|>\\n{SYSTEM_MSG}</s>\\n<|user|>\\n{question}</s>\\n<|assistant|>\\n'\n",
    "    inputs = tokenizer(prompt, return_tensors='pt').to(device)\n",
    "    with torch.no_grad():\n",
    "        output = model.generate(\n",
    "            **inputs, max_new_tokens=400, temperature=0.7,\n",
    "            do_sample=True, pad_token_id=tokenizer.eos_token_id,\n",
    "            repetition_penalty=1.1,\n",
    "        )\n",
    "    response = tokenizer.decode(\n",
    "        output[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
    "\n",
    "    eval_results.append({'specialty': specialty, 'question': question, 'response': response})\n",
    "    print(f'[{specialty}]')\n",
    "    print(f'Q: {question[:120]}...' if len(question) > 120 else f'Q: {question}')\n",
    "    print(f'A: {response[:600]}')\n",
    "    print('─' * 70 + '\\n')\n",
    "\n",
    "# Save eval results\n",
    "eval_path = os.path.join(RESULTS_DIR, 'eval_responses.json')\n",
    "with open(eval_path, 'w') as f:\n",
    "    json.dump(eval_results, f, indent=2)\n",
    "print(f'Evaluation saved: {eval_path}')\n",
    "\n",
    "del model, base\n",
    "if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
)

# ── Cell 9: Interactive ──────────────────────────────────────────────────────
code(
    "# ── Interactive Chat ──────────────────────────────────────────────────────\n",
    "print('Loading model for interactive use...')\n",
    "base  = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "model = PeftModel.from_pretrained(base, MODEL_DIR)\n",
    "model.to(device).eval()\n",
    "print('Ready. Type a clinical question. Type \"quit\" to exit.\\n')\n",
    "\n",
    "while True:\n",
    "    question = input('Clinical question: ').strip()\n",
    "    if question.lower() in ('quit', 'exit', 'q', ''):\n",
    "        break\n",
    "    prompt  = f'<|system|>\\n{SYSTEM_MSG}</s>\\n<|user|>\\n{question}</s>\\n<|assistant|>\\n'\n",
    "    inputs  = tokenizer(prompt, return_tensors='pt').to(device)\n",
    "    with torch.no_grad():\n",
    "        output = model.generate(\n",
    "            **inputs, max_new_tokens=500, temperature=0.7,\n",
    "            do_sample=True, pad_token_id=tokenizer.eos_token_id,\n",
    "            repetition_penalty=1.1,\n",
    "        )\n",
    "    ans = tokenizer.decode(output[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
    "    print(f'\\n{\"═\"*65}\\n{ans}\\n{\"═\"*65}\\n')\n",
)

# ── Build notebook ───────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "gpuType": "T4",
            "toc_visible": True,
        },
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU",
    },
    "cells": cells,
}

out = "/sessions/magical-serene-newton/mnt/Downloads/medtrace/MedTrace_FL_Colab.ipynb"
with open(out, "w") as f:
    json.dump(notebook, f, indent=1)
print(f"Notebook written: {out}")
print(f"Cells: {len(cells)}")
