"""Build a bulletproof FL Colab notebook — all-in-one with checkpointing."""
import json

cells = []
def md(lines): cells.append({"cell_type": "markdown", "metadata": {}, "source": lines})
def code(lines): cells.append({"cell_type": "code", "metadata": {}, "source": lines, "execution_count": None, "outputs": []})

# ─── Cell 1: Title ─────────────────────────
md([
    "# MedTrace Federated Learning\n",
    "## Privacy-Preserving Medical AI — 10-Hour Training with Checkpointing\n",
    "\n",
    "**Run All cells. If disconnected, just Run All again — resumes automatically.**\n",
])

# ─── Cell 2: Install + GPU Check + Mount Drive ──────────
code([
    "!pip install -q transformers datasets peft accelerate torch\n",
    "import torch, os\n",
    "if torch.cuda.is_available():\n",
    "    print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
    "    print(f'Memory: {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')\n",
    "else:\n",
    "    print('WARNING: No GPU. Go to Runtime > Change runtime type > T4 GPU')\n",
    "\n",
    "from google.colab import drive\n",
    "if not os.path.exists('/content/drive/MyDrive'):\n",
    "    drive.mount('/content/drive')\n",
    "else:\n",
    "    print('Drive already mounted')\n",
    "print('Setup complete')\n",
])

# ─── Cell 4: ALL imports + config + classes + training loop ──────
# One giant cell so nothing can go out of scope
code([
    "# ================================================================\n",
    "# MEDTRACE FEDERATED LEARNING — COMPLETE TRAINING SCRIPT\n",
    "# All code in one cell to prevent scope issues on reconnect\n",
    "# ================================================================\n",
    "\n",
    "import os, json, time, copy\n",
    "import torch\n",
    "import numpy as np\n",
    "from collections import OrderedDict\n",
    "from datasets import load_dataset\n",
    "from transformers import (\n",
    "    AutoTokenizer, AutoModelForCausalLM,\n",
    "    TrainingArguments, Trainer, DataCollatorForLanguageModeling\n",
    ")\n",
    "from peft import LoraConfig, get_peft_model, PeftModel\n",
    "\n",
    "# ─── CONFIG ───────────────────────────────────────────────\n",
    "BASE_MODEL = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'\n",
    "NUM_HOSPITALS = 3\n",
    "FL_ROUNDS = 20\n",
    "LOCAL_EPOCHS = 1\n",
    "LORA_R = 8\n",
    "LORA_ALPHA = 16\n",
    "BATCH_SIZE = 4\n",
    "MAX_LENGTH = 512\n",
    "LR = 2e-4\n",
    "DP_EPSILON = 8.0\n",
    "DP_DELTA = 1e-5\n",
    "DP_MAX_GRAD_NORM = 1.0\n",
    "SYSTEM_MSG = 'You are MedTrace, a federated clinical reasoning system. Generate step-by-step auditable diagnostic reasoning chains.'\n",
    "\n",
    "HOSPITAL_CONFIGS = {\n",
    "    'hospital_A': {'name': 'Metro General (Cardiology)', 'kw': ['heart','cardiac','coronary','chest pain','myocardial','arrhythmia','angina','aortic'], 'samples': 1500},\n",
    "    'hospital_B': {'name': 'Royal London (Neurology)',   'kw': ['brain','neuro','seizure','headache','stroke','cognitive','dementia','nerve'], 'samples': 1200},\n",
    "    'hospital_C': {'name': 'AIIMS Delhi (Infectious)',   'kw': ['infection','fever','bacteria','virus','antibiotic','sepsis','tuberculosis','malaria'], 'samples': 1300},\n",
    "}\n",
    "\n",
    "CHECKPOINT_DIR = '/content/drive/MyDrive/MedTrace/fl_checkpoints'\n",
    "SAVE_DIR = '/content/drive/MyDrive/MedTrace/federated-global'\n",
    "os.makedirs(CHECKPOINT_DIR, exist_ok=True)\n",
    "os.makedirs(SAVE_DIR, exist_ok=True)\n",
    "\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "print(f'Device: {device} | Rounds: {FL_ROUNDS} | Epochs: {LOCAL_EPOCHS}')\n",
    "\n",
    "# ─── CHECKPOINT FUNCTIONS ─────────────────────────────────\n",
    "def save_checkpoint(weights, round_num):\n",
    "    path = os.path.join(CHECKPOINT_DIR, f'round_{round_num}.pt')\n",
    "    torch.save(weights, path)\n",
    "    with open(os.path.join(CHECKPOINT_DIR, 'last_round.txt'), 'w') as f:\n",
    "        f.write(str(round_num))\n",
    "    print(f'  CHECKPOINT SAVED: round_{round_num}.pt')\n",
    "\n",
    "def load_checkpoint():\n",
    "    marker = os.path.join(CHECKPOINT_DIR, 'last_round.txt')\n",
    "    if not os.path.exists(marker):\n",
    "        return None, -1\n",
    "    with open(marker) as f:\n",
    "        last = int(f.read().strip())\n",
    "    path = os.path.join(CHECKPOINT_DIR, f'round_{last}.pt')\n",
    "    if os.path.exists(path):\n",
    "        w = torch.load(path, map_location='cpu', weights_only=False)\n",
    "        print(f'  RESUMED from checkpoint: round {last+1}')\n",
    "        return w, last\n",
    "    return None, -1\n",
    "\n",
    "# ─── HOSPITAL CLIENT ─────────────────────────────────────\n",
    "class HospitalClient:\n",
    "    def __init__(self, hid, config):\n",
    "        self.hid = hid\n",
    "        self.name = config['name']\n",
    "        self.kw = config['kw']\n",
    "        self.num_samples = config['samples']\n",
    "        self.privacy_spent = 0.0\n",
    "        print(f'  Hospital: {self.name}')\n",
    "\n",
    "    def prepare_data(self, full_dataset, round_num):\n",
    "        spec_idx, gen_idx = [], []\n",
    "        for i, ex in enumerate(full_dataset):\n",
    "            q = ex['question'].lower()\n",
    "            if any(k in q for k in self.kw):\n",
    "                spec_idx.append(i)\n",
    "            else:\n",
    "                gen_idx.append(i)\n",
    "        seed = abs(hash(self.hid) + round_num) % (2**32)\n",
    "        rng = np.random.RandomState(seed)\n",
    "        n_spec = min(int(self.num_samples * 0.6), len(spec_idx))\n",
    "        n_gen = self.num_samples - n_spec\n",
    "        chosen = []\n",
    "        if n_spec > 0 and len(spec_idx) > 0:\n",
    "            chosen.extend(rng.choice(spec_idx, n_spec, replace=True).tolist())\n",
    "        if n_gen > 0 and len(gen_idx) > 0:\n",
    "            chosen.extend(rng.choice(gen_idx, min(n_gen, len(gen_idx)), replace=True).tolist())\n",
    "        seed2 = abs(hash(self.hid) + round_num + 42) % (2**32)\n",
    "        rng2 = np.random.RandomState(seed2)\n",
    "        rng2.shuffle(chosen)\n",
    "        self.local_data = full_dataset.select(chosen[:self.num_samples])\n",
    "        print(f'  {self.name}: {len(self.local_data)} samples ({n_spec} specialty)')\n",
    "\n",
    "    def train_local(self, global_weights, tokenizer, round_num):\n",
    "        print(f'  Training {self.name} (Round {round_num+1})...')\n",
    "        t0 = time.time()\n",
    "        base = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "        lora_cfg = LoraConfig(r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=0.05,\n",
    "                              target_modules=['q_proj','v_proj'], bias='none', task_type='CAUSAL_LM')\n",
    "        model = get_peft_model(base, lora_cfg)\n",
    "        if global_weights is not None:\n",
    "            model.load_state_dict(global_weights, strict=False)\n",
    "        model.to(device)\n",
    "\n",
    "        def tokenize(examples):\n",
    "            prompts = [f'<|system|>\\n{SYSTEM_MSG}</s>\\n<|user|>\\n{q}</s>\\n<|assistant|>\\n' for q in examples['question']]\n",
    "            enc = tokenizer(prompts, truncation=True, max_length=MAX_LENGTH, padding='max_length')\n",
    "            enc['labels'] = enc['input_ids'].copy()\n",
    "            return enc\n",
    "\n",
    "        tok_data = self.local_data.map(tokenize, batched=True, remove_columns=self.local_data.column_names)\n",
    "        tok_data.set_format('torch')\n",
    "        out_dir = f'/content/fl_temp/{self.hid}/round_{round_num}'\n",
    "        os.makedirs(out_dir, exist_ok=True)\n",
    "        args = TrainingArguments(\n",
    "            output_dir=out_dir, num_train_epochs=LOCAL_EPOCHS,\n",
    "            per_device_train_batch_size=BATCH_SIZE, learning_rate=LR,\n",
    "            warmup_steps=10, logging_steps=5, save_strategy='no',\n",
    "            report_to='none', fp16=torch.cuda.is_available(),\n",
    "            gradient_checkpointing=True, gradient_accumulation_steps=2,\n",
    "            dataloader_pin_memory=False)\n",
    "        trainer = Trainer(model=model, args=args, train_dataset=tok_data,\n",
    "                         data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False))\n",
    "        trainer.train()\n",
    "        elapsed = time.time() - t0\n",
    "        loss = trainer.state.log_history[-1].get('train_loss', 0) if trainer.state.log_history else 0\n",
    "\n",
    "        # Extract LoRA weights only\n",
    "        lora_w = OrderedDict()\n",
    "        for name, p in model.named_parameters():\n",
    "            if 'lora_' in name:\n",
    "                lora_w[name] = p.detach().cpu().clone()\n",
    "\n",
    "        # Differential privacy noise\n",
    "        sigma = DP_MAX_GRAD_NORM * np.sqrt(2 * np.log(1.25 / DP_DELTA)) / DP_EPSILON\n",
    "        for name in lora_w:\n",
    "            norm = torch.norm(lora_w[name])\n",
    "            if norm > DP_MAX_GRAD_NORM:\n",
    "                lora_w[name] = lora_w[name] * (DP_MAX_GRAD_NORM / norm)\n",
    "            lora_w[name] = lora_w[name] + torch.randn_like(lora_w[name]) * sigma\n",
    "        self.privacy_spent += DP_EPSILON / FL_ROUNDS\n",
    "        n_params = sum(p.numel() for p in lora_w.values())\n",
    "        print(f'  DONE: Loss={loss:.4f} Time={elapsed:.1f}s Shared={n_params:,} params')\n",
    "        print(f'  DP noise sigma={sigma:.4f} | Privacy: {self.privacy_spent:.2f}/{DP_EPSILON}')\n",
    "        del model, base, trainer\n",
    "        if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
    "        return lora_w, {'hospital': self.name, 'loss': loss, 'samples': len(self.local_data), 'time': elapsed}\n",
    "\n",
    "# ─── FEDERATED SERVER ─────────────────────────────────────\n",
    "class FederatedServer:\n",
    "    def __init__(self):\n",
    "        self.global_weights = None\n",
    "        print('Aggregation Server ready')\n",
    "\n",
    "    def init_global_model(self):\n",
    "        base = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "        lora_cfg = LoraConfig(r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=0.05,\n",
    "                              target_modules=['q_proj','v_proj'], bias='none', task_type='CAUSAL_LM')\n",
    "        model = get_peft_model(base, lora_cfg)\n",
    "        self.global_weights = OrderedDict()\n",
    "        for name, p in model.named_parameters():\n",
    "            if 'lora_' in name:\n",
    "                self.global_weights[name] = p.detach().cpu().clone()\n",
    "        n = sum(p.numel() for p in self.global_weights.values())\n",
    "        print(f'Global LoRA params: {n:,}')\n",
    "        del model, base\n",
    "        if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
    "        return self.global_weights\n",
    "\n",
    "    def aggregate(self, client_updates, round_num):\n",
    "        print(f'Aggregating Round {round_num+1} (FedAvg)...')\n",
    "        wl, counts, names = [], [], []\n",
    "        for hid, (w, m) in client_updates.items():\n",
    "            wl.append(w); counts.append(m['samples']); names.append(m['hospital'])\n",
    "        total = sum(counts)\n",
    "        fracs = [c/total for c in counts]\n",
    "        for n, f, c in zip(names, fracs, counts):\n",
    "            print(f'  {n}: weight={f:.3f} ({c} samples)')\n",
    "        agg = OrderedDict()\n",
    "        for key in wl[0]:\n",
    "            agg[key] = sum(fracs[i] * wl[i][key] for i in range(len(wl)))\n",
    "        self.global_weights = agg\n",
    "        div = sum(torch.norm(wl[i][k] - agg[k]).item()**2\n",
    "                  for k in agg for i in range(len(wl))) / (len(agg)*len(wl))\n",
    "        print(f'  Weight divergence: {div:.6f}')\n",
    "        return self.global_weights\n",
    "\n",
    "# ─── LOAD DATA ────────────────────────────────────────────\n",
    "print('Loading MedQA USMLE dataset...')\n",
    "dataset = load_dataset('GBaker/MedQA-USMLE-4-options', split='train')\n",
    "print(f'Total: {len(dataset)} examples')\n",
    "\n",
    "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)\n",
    "if tokenizer.pad_token is None:\n",
    "    tokenizer.pad_token = tokenizer.eos_token\n",
    "\n",
    "# ─── INIT SERVER + RESUME ─────────────────────────────────\n",
    "print('\\n' + '='*70)\n",
    "print('  MedTrace Federated Learning')\n",
    "print('='*70)\n",
    "\n",
    "server = FederatedServer()\n",
    "global_w, last_round = load_checkpoint()\n",
    "start_round = last_round + 1\n",
    "\n",
    "if global_w is None:\n",
    "    print('No checkpoint found — starting fresh')\n",
    "    global_w = server.init_global_model()\n",
    "    start_round = 0\n",
    "else:\n",
    "    print(f'Will resume from round {start_round + 1}/{FL_ROUNDS}')\n",
    "\n",
    "if start_round >= FL_ROUNDS:\n",
    "    print('All rounds already complete! Skip to evaluation.')\n",
    "else:\n",
    "    hospitals = {}\n",
    "    print('\\nInitializing hospitals...')\n",
    "    for hid, hcfg in HOSPITAL_CONFIGS.items():\n",
    "        hospitals[hid] = HospitalClient(hid, hcfg)\n",
    "\n",
    "    total_t0 = time.time()\n",
    "    for r in range(start_round, FL_ROUNDS):\n",
    "        print(f'\\n{\"=\"*70}')\n",
    "        print(f'  ROUND {r+1}/{FL_ROUNDS}')\n",
    "        print(f'{\"=\"*70}')\n",
    "        for hid, client in hospitals.items():\n",
    "            client.prepare_data(dataset, r)\n",
    "        updates = {}\n",
    "        for hid, client in hospitals.items():\n",
    "            w, m = client.train_local(global_w, tokenizer, r)\n",
    "            updates[hid] = (w, m)\n",
    "        global_w = server.aggregate(updates, r)\n",
    "        save_checkpoint(global_w, r)\n",
    "\n",
    "    total_time = time.time() - total_t0\n",
    "    print(f'\\n{\"=\"*70}')\n",
    "    print(f'  TRAINING COMPLETE! Total: {total_time:.1f}s')\n",
    "    print(f'{\"=\"*70}')\n",
    "\n",
    "# ─── SAVE FINAL MODEL TO DRIVE ───────────────────────────\n",
    "print('\\nSaving final federated model to Drive...')\n",
    "base = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "lora_cfg = LoraConfig(r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=0.05,\n",
    "                      target_modules=['q_proj','v_proj'], bias='none', task_type='CAUSAL_LM')\n",
    "model = get_peft_model(base, lora_cfg)\n",
    "model.load_state_dict(global_w, strict=False)\n",
    "model.save_pretrained(SAVE_DIR)\n",
    "tokenizer.save_pretrained(SAVE_DIR)\n",
    "metadata = {'architecture': 'MedTrace Federated Learning', 'base_model': BASE_MODEL,\n",
    "            'hospitals': NUM_HOSPITALS, 'rounds': FL_ROUNDS, 'dp_epsilon': DP_EPSILON,\n",
    "            'local_epochs': LOCAL_EPOCHS}\n",
    "with open(os.path.join(SAVE_DIR, 'fl_metadata.json'), 'w') as f:\n",
    "    json.dump(metadata, f, indent=2)\n",
    "print(f'Model saved to: {SAVE_DIR}')\n",
    "del model, base\n",
    "if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
])

# ─── Cell 5: Evaluate ────────────────────
code([
    "# ================================================================\n",
    "# EVALUATE FEDERATED MODEL\n",
    "# ================================================================\n",
    "print('Loading federated model for evaluation...')\n",
    "base = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "model = PeftModel.from_pretrained(base, SAVE_DIR)\n",
    "model.to(device)\n",
    "model.eval()\n",
    "\n",
    "questions = [\n",
    "    'A 55-year-old woman has sudden left-sided weakness. CT shows no hemorrhage. Next step?',\n",
    "    'A 30-year-old man has high fever, neck stiffness, photophobia. Diagnosis?',\n",
    "    'A 65-year-old diabetic has crushing chest pain, elevated troponin. Management?',\n",
    "]\n",
    "\n",
    "for q in questions:\n",
    "    prompt = f'<|system|>\\n{SYSTEM_MSG}</s>\\n<|user|>\\n{q}</s>\\n<|assistant|>\\n'\n",
    "    inputs = tokenizer(prompt, return_tensors='pt').to(device)\n",
    "    with torch.no_grad():\n",
    "        out = model.generate(**inputs, max_new_tokens=300, temperature=0.7,\n",
    "                            do_sample=True, pad_token_id=tokenizer.eos_token_id)\n",
    "    ans = tokenizer.decode(out[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
    "    print(f'\\nQ: {q}')\n",
    "    print(f'A: {ans[:500]}')\n",
    "    print('-' * 60)\n",
    "del model, base\n",
    "if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
])

# ─── Cell 6: Interactive ─────────────────
code([
    "# ================================================================\n",
    "# INTERACTIVE MODE — Ask the federated model anything\n",
    "# ================================================================\n",
    "print('Loading model...')\n",
    "base = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float32)\n",
    "model = PeftModel.from_pretrained(base, SAVE_DIR)\n",
    "model.to(device)\n",
    "model.eval()\n",
    "print('Ready! Type your question below.\\n')\n",
    "\n",
    "while True:\n",
    "    question = input('Your question (quit to stop): ')\n",
    "    if question.lower() == 'quit': break\n",
    "    prompt = f'<|system|>\\n{SYSTEM_MSG}</s>\\n<|user|>\\n{question}</s>\\n<|assistant|>\\n'\n",
    "    inputs = tokenizer(prompt, return_tensors='pt').to(device)\n",
    "    with torch.no_grad():\n",
    "        out = model.generate(**inputs, max_new_tokens=400, temperature=0.7,\n",
    "                            do_sample=True, pad_token_id=tokenizer.eos_token_id)\n",
    "    ans = tokenizer.decode(out[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
    "    print(f'\\n{\"=\"*60}\\n{ans}\\n{\"=\"*60}\\n')\n",
])

# Build notebook
notebook = {
    "nbformat": 4, "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU"
    },
    "cells": cells
}

out = "/sessions/magical-serene-newton/mnt/Downloads/medtrace/MedTrace_FL_Colab.ipynb"
with open(out, "w") as f:
    json.dump(notebook, f, indent=1)
print(f"Notebook saved: {out}")
